### ISSUE TITLE
metadata image url

### ISSUE THREAD

**Issue by Erwan-Cloitre** [NotLuksus/nft-art-generator#1]
Hi ! i got this when i create the metadata for the image url --> 'https://gateway.pinata.cloud/ipfs/.../0'
But I want a .png like this --> 'https://gateway.pinata.cloud/ipfs/.../0.png'
I try to change the index.js, ligne 376 'image: imageUrl + id,' to -> 'image: imageUrl + id + '.png','
But nothing change u can help me ?

**Comment by NotLuksus** [comment]
That should work. Try deleting the output folder if you haven't already and re run the script. Also how did you install the script and where did you change the line of code?

**Comment by Erwan-Cloitre** [comment]
I try again and not working, i export ur folder and i run 'npm install -g nft-art-generator', i change the file index.js in bin folder

**Comment by NotLuksus** [comment]
Alright!
The problem is that you don't actually modify the code that you are using.
What you wanna do is first of all uninstall the old package you installed by using npm remove nft-art-generator.
Then you wanna go into the folder where you changed the code and open a terminal there.
In there you need to type `npm install -g .` this will install your local edited version of the package.
Then everything should work fine.
